# roles/mariadb/tasks/main.yml
---

- name: Include distribution dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "RedHat_base.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: root-password.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: optimize-centos7.yml
  when: "mariadb_distro | bool == false"
